
name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
      # run: |
      #   docker run \
      #   -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
      #   jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && ./deploy.sh"
    - name: Set up jekyll
      run: gem install jekyll
    - name: Build and delopy blog
      run: ./deploy.sh